version: '3.4'

services:
  postgres-db:
   container_name: ${CONTAINER_NAME_PREFIX_BACKEND}_postgres_db
   image: postgres:13.5-alpine
   restart: always
   env_file: .env
   volumes:
     - ./docker/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
   ports:
      - 5432:5432
   networks: 
      - ${CONTAINER_NAME_PREFIX_BACKEND}

networks:
  backend-common:
    driver: bridge
